import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "enscribe-api",
    },
    {
      type: "category",
      label: "Organizations",
      link: {
        type: "doc",
        id: "organizations",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "create-organization",
          label: "Create an organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-organization-config",
          label: "Get organization config",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Invitations",
      link: {
        type: "doc",
        id: "invitations",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "create-organization-invitation",
          label: "Create an organization invitation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Members",
      link: {
        type: "doc",
        id: "members",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "update-organization-member-role",
          label: "Update an organization member role",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "API keys",
      link: {
        type: "doc",
        id: "api-keys",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "list-organization-api-keys",
          label: "List organization API keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-organization-api-key",
          label: "Create an organization API key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "revoke-organization-api-key",
          label: "Revoke an organization API key",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Namespaces",
      link: {
        type: "doc",
        id: "namespaces",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "create-namespace",
          label: "Create a namespace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-namespace-config",
          label: "Get namespace config",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-namespace",
          label: "Delete a namespace",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Contracts",
      link: {
        type: "doc",
        id: "contracts",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "list-contracts",
          label: "List contracts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-contract",
          label: "Add a contract",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Activity",
      link: {
        type: "doc",
        id: "activity",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "list-organization-activity",
          label: "List organization activity",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Metadata",
      link: {
        type: "doc",
        id: "metadata",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "execute-metadata-changes",
          label: "Execute staged metadata changes",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Subnames",
      link: {
        type: "doc",
        id: "subnames",
      },
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "list-subnames",
          label: "List subnames",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-subname",
          label: "Create a subname",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-subname",
          label: "Delete a subname",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "schemas/apierrorobject",
          label: "ApiErrorObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/apienvelopeerrorresponse",
          label: "ApiEnvelopeErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/legacyerrorresponse",
          label: "LegacyErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/paginationmeta",
          label: "PaginationMeta",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/networkmode",
          label: "NetworkMode",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/managermode",
          label: "ManagerMode",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/contracttype",
          label: "ContractType",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/contractstatus",
          label: "ContractStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/namingstatus",
          label: "NamingStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadatastatus",
          label: "MetadataStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/operationtype",
          label: "OperationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/operationstatus",
          label: "OperationStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/apiscope",
          label: "ApiScope",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createorganizationrequest",
          label: "CreateOrganizationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createorganizationresponse",
          label: "CreateOrganizationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createorganizationapiresponse",
          label: "CreateOrganizationApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/namespacesummary",
          label: "NamespaceSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/organizationconfigresponse",
          label: "OrganizationConfigResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createorganizationinvitationrequest",
          label: "CreateOrganizationInvitationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/organizationinvitationresponse",
          label: "OrganizationInvitationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/organizationinvitationapiresponse",
          label: "OrganizationInvitationApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/updateorganizationmemberrolerequest",
          label: "UpdateOrganizationMemberRoleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/organizationmemberroleresponse",
          label: "OrganizationMemberRoleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/organizationmemberroleapiresponse",
          label: "OrganizationMemberRoleApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/orgapikeysummary",
          label: "OrgApiKeySummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createorganizationapikeyrequest",
          label: "CreateOrganizationApiKeyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createorganizationapikeyresult",
          label: "CreateOrganizationApiKeyResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/organizationapikeylistapiresponse",
          label: "OrganizationApiKeyListApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createorganizationapikeyapiresponse",
          label: "CreateOrganizationApiKeyApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/organizationapikeyapiresponse",
          label: "OrganizationApiKeyApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/namespace",
          label: "Namespace",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createnamespacerequest",
          label: "CreateNamespaceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createnamespaceresponse",
          label: "CreateNamespaceResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/deletesuccessresponse",
          label: "DeleteSuccessResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/contract",
          label: "Contract",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/addcontractrequest",
          label: "AddContractRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadatachanges",
          label: "MetadataChanges",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/addressrecordchange",
          label: "AddressRecordChange",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadatachange",
          label: "MetadataChange",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/namingoperation",
          label: "NamingOperation",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadataexecuterequest",
          label: "MetadataExecuteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/stagedsubnamecreate",
          label: "StagedSubnameCreate",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/stagedsubnamedelete",
          label: "StagedSubnameDelete",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadatachangerequest",
          label: "MetadataChangeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/phaseresult",
          label: "PhaseResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadataphaseresult",
          label: "MetadataPhaseResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadataexecuteresults",
          label: "MetadataExecuteResults",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/phaseerror",
          label: "PhaseError",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/metadataexecuteresponse",
          label: "MetadataExecuteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamesummary",
          label: "SubnameSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamelistdata",
          label: "SubnameListData",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamelistapiresponse",
          label: "SubnameListApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/createsubnamerequest",
          label: "CreateSubnameRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/deletesubnamerequest",
          label: "DeleteSubnameRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamecreatedirectresult",
          label: "SubnameCreateDirectResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamecreatesaferesult",
          label: "SubnameCreateSafeResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamedeletedirectresult",
          label: "SubnameDeleteDirectResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamedeletesaferesult",
          label: "SubnameDeleteSafeResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamecreateapiresponse",
          label: "SubnameCreateApiResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "schemas/subnamedeleteapiresponse",
          label: "SubnameDeleteApiResponse",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
