export type NetworkConfig = {
  name: string
  ENSCRIBE_CONTRACT: string
  ENSCRIBE_V2_CONTRACT: string
  ENS_REGISTRY: string
  BASE_REGISTRAR: string
  NAME_WRAPPER: string
  REVERSE_REGISTRAR: string
  L2_REVERSE_REGISTRAR: string
  PUBLIC_RESOLVER: string
  ENSCRIBE_DOMAIN: string
  ETHERSCAN_URL: string
  ENS_APP_URL: string
  CHAINLENS_URL: string
  BLOCKSCOUT_URL: string
  RPC_ENDPOINT: string
  SUBGRAPH_API: string
  COIN_TYPE: string
}

export const CONTRACTS: Record<number, NetworkConfig> = {
  // mainnet
  1: {
    name: 'Ethereum Mainnet',
    ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER || '',
    REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR || '',
    L2_REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE || '',
  },
  // Sepolia Testnet
  11155111: {
    name: 'Sepolia Testnet',
    ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_SEPOLIA || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_SEPOLIA || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_SEPOLIA || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_SEPOLIA || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_SEPOLIA || '',
    REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_SEPOLIA || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_SEPOLIA || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_SEPOLIA || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_SEPOLIA || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_SEPOLIA || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_SEPOLIA || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_SEPOLIA || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_SEPOLIA || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_SEPOLIA || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_SEPOLIA || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_SEPOLIA || '',
  },

  // Linea mainnet
  59144: {
    name: 'Linea Mainnet',
    ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_LINEA || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_LINEA || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_LINEA || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_LINEA || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_LINEA || '',
    REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_LINEA || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_LINEA || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_LINEA || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_LINEA || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_LINEA || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_LINEA || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_LINEA || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_LINEA || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_LINEA || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_LINEA || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_LINEA || '',
  },

  // Linea Sepolia Testnet
  59141: {
    name: 'Linea Sepolia Testnet',
    ENSCRIBE_CONTRACT:
      process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_LINEA_SEPOLIA || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_LINEA_SEPOLIA || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_LINEA_SEPOLIA || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_LINEA_SEPOLIA ||
      '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_LINEA_SEPOLIA || '',
    REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_LINEA_SEPOLIA || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_LINEA_SEPOLIA || '',
    PUBLIC_RESOLVER:
      process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_LINEA_SEPOLIA || '',
    ENSCRIBE_DOMAIN:
      process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_LINEA_SEPOLIA || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_LINEA_SEPOLIA || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_LINEA_SEPOLIA || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_LINEA_SEPOLIA || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_LINEA_SEPOLIA || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_LINEA_SEPOLIA || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_LINEA_SEPOLIA || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_LINEA_SEPOLIA || '',
  },

  // BASE mainnet
  8453: {
    name: 'Base Mainnet',
    ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_BASE || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_BASE || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_BASE || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_BASE || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_BASE || '',
    REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_BASE || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_BASE || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_BASE || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_BASE || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_BASE || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_BASE || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_BASE || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_BASE || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_BASE || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_BASE || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_BASE || '',
  },

  // BASE Sepolia Testnet
  84532: {
    name: 'Base Sepolia Testnet',
    ENSCRIBE_CONTRACT:
      process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_BASE_SEPOLIA || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_BASE_SEPOLIA || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_BASE_SEPOLIA || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_BASE_SEPOLIA ||
      '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_BASE_SEPOLIA || '',
    REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_BASE_SEPOLIA || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_BASE_SEPOLIA || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_BASE_SEPOLIA || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_BASE_SEPOLIA || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_BASE_SEPOLIA || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_BASE_SEPOLIA || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_BASE_SEPOLIA || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_BASE_SEPOLIA || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_BASE_SEPOLIA || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_BASE_SEPOLIA || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_BASE_SEPOLIA || '',
  },

  // Optimism Mainnet
  10: {
    name: 'Optimism Mainnet',
    ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_OPTIMISM || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_OPTIMISM || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_OPTIMISM || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_OPTIMISM || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_OPTIMISM || '',
    REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_OPTIMISM || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_OPTIMISM || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_OPTIMISM || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_OPTIMISM || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_OPTIMISM || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_OPTIMISM || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_OPTIMISM || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_OPTIMISM || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_OPTIMISM || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_OPTIMISM || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_OPTIMISM || '',
  },

  // Optimism Sepolia Testnet
  11155420: {
    name: 'Optimism Sepolia Testnet',
    ENSCRIBE_CONTRACT:
      process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_OPTIMISM_SEPOLIA || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_OPTIMISM_SEPOLIA || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_OPTIMISM_SEPOLIA || '',
    BASE_REGISTRAR:
      process.env
        .NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_OPTIMISM_SEPOLIA || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_OPTIMISM_SEPOLIA || '',
    REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_OPTIMISM_SEPOLIA || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_OPTIMISM_SEPOLIA || '',
    PUBLIC_RESOLVER:
      process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_OPTIMISM_SEPOLIA || '',
    ENSCRIBE_DOMAIN:
      process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_OPTIMISM_SEPOLIA || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_OPTIMISM_SEPOLIA || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_OPTIMISM_SEPOLIA || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_OPTIMISM_SEPOLIA || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_OPTIMISM_SEPOLIA || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_OPTIMISM_SEPOLIA || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_OPTIMISM_SEPOLIA || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_OPTIMISM_SEPOLIA || '',
  },

  // Arbitrum Mainnet
  42161: {
    name: 'Arbitrum Mainnet',
    ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_ARBITRUM || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_ARBITRUM || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_ARBITRUM || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_ARBITRUM || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_ARBITRUM || '',
    REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_ARBITRUM || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_ARBITRUM || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_ARBITRUM || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_ARBITRUM || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_ARBITRUM || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_ARBITRUM || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_ARBITRUM || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_ARBITRUM || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_ARBITRUM || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_ARBITRUM || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_ARBITRUM || '',
  },

  // Arbitrum Sepolia Testnet
  421614: {
    name: 'Arbitrum Sepolia Testnet',
    ENSCRIBE_CONTRACT:
      process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_ARBITRUM_SEPOLIA || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_ARBITRUM_SEPOLIA || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_ARBITRUM_SEPOLIA || '',
    BASE_REGISTRAR:
      process.env
        .NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_ARBITRUM_SEPOLIA || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_ARBITRUM_SEPOLIA || '',
    REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_ARBITRUM_SEPOLIA || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_ARBITRUM_SEPOLIA || '',
    PUBLIC_RESOLVER:
      process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_ARBITRUM_SEPOLIA || '',
    ENSCRIBE_DOMAIN:
      process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_ARBITRUM_SEPOLIA || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_ARBITRUM_SEPOLIA || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_ARBITRUM_SEPOLIA || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_ARBITRUM_SEPOLIA || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_ARBITRUM_SEPOLIA || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_ARBITRUM_SEPOLIA || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_ARBITRUM_SEPOLIA || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_ARBITRUM_SEPOLIA || '',
  },

  // Scroll Mainnet
  534352: {
    name: 'Scroll Mainnet',
    ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_SCROLL || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_SCROLL || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_SCROLL || '',
    BASE_REGISTRAR:
      process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_SCROLL || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_SCROLL || '',
    REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_SCROLL || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_SCROLL || '',
    PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_SCROLL || '',
    ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_SCROLL || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_SCROLL || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_SCROLL || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_SCROLL || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_SCROLL || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_SCROLL || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_SCROLL || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_SCROLL || '',
  },

  // Scroll Sepolia Testnet
  534351: {
    name: 'Scroll Sepolia Testnet',
    ENSCRIBE_CONTRACT:
      process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_SCROLL_SEPOLIA || '',
    ENSCRIBE_V2_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_V2_CONTRACT_SCROLL_SEPOLIA || '',
    ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_SCROLL_SEPOLIA || '',
    BASE_REGISTRAR:
      process.env
        .NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_SCROLL_SEPOLIA || '',
    NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_SCROLL_SEPOLIA || '',
    REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_SCROLL_SEPOLIA || '',
    L2_REVERSE_REGISTRAR:
      process.env.NEXT_PUBLIC_L2_REVERSE_REGISTRAR_SCROLL_SEPOLIA || '',
    PUBLIC_RESOLVER:
      process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_SCROLL_SEPOLIA || '',
    ENSCRIBE_DOMAIN:
      process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_SCROLL_SEPOLIA || '',
    ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_SCROLL_SEPOLIA || '',
    ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_SCROLL_SEPOLIA || '',
    CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_SCROLL_SEPOLIA || '',
    BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_SCROLL_SEPOLIA || '',
    RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_SCROLL_SEPOLIA || '',
    SUBGRAPH_API: process.env.NEXT_PUBLIC_SUBGRAPH_API_SCROLL_SEPOLIA || '',
    COIN_TYPE: process.env.NEXT_PUBLIC_ENS_COINTYPE_SCROLL_SEPOLIA || '',
  },
}

export const TOPIC0 = process.env.NEXT_PUBLIC_TOPIC0_SET_NAME

export const ETHERSCAN_API = process.env.NEXT_PUBLIC_ETHERSCAN_API

export const SOURCIFY_API = process.env.NEXT_PUBLIC_SOURCIFY_API
export const SOURCIFY_URL = process.env.NEXT_PUBLIC_SOURCIFY_URL

export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
export const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_KEY || ''

export enum CHAINS {
  MAINNET = 1,
  SEPOLIA = 11155111,
  LINEA = 59144,
  LINEA_SEPOLIA = 59141,
  BASE = 8453,
  BASE_SEPOLIA = 84532,
  OPTIMISM = 10,
  OPTIMISM_SEPOLIA = 11155420,
  ARBITRUM = 42161,
  ARBITRUM_SEPOLIA = 421614,
  SCROLL = 534352,
  SCROLL_SEPOLIA = 534351,
}

export const METRICS_URL = '/api/v1/metrics'
export const NAME_GEN_URL = '/api/v1/name'

export const OLI_ATTESTATION_URL = 'https://www.openlabelsinitiative.org/attest'
export const OLI_SEARCH_URL = 'https://www.openlabelsinitiative.org/search'
export const OLI_GQL_URL = 'https://base.easscan.org/graphql'

export const nouns = [
  'able',
  'account',
  'achieve',
  'achiever',
  'acoustics',
  'act',
  'action',
  'activity',
  'actor',
  'addition',
  'adjustment',
  'advertisement',
  'advice',
  'aftermath',
  'afternoon',
  'afterthought',
  'agreement',
  'air',
  'airplane',
  'airport',
  'alarm',
  'alley',
  'amount',
  'amusement',
  'anger',
  'angle',
  'animal',
  'answer',
  'ant',
  'ants',
  'apparatus',
  'apparel',
  'apple',
  'apples',
  'appliance',
  'approval',
  'arch',
  'argument',
  'arithmetic',
  'arm',
  'army',
  'art',
  'attack',
  'attempt',
  'attention',
  'attraction',
  'aunt',
  'authority',
  'babies',
  'baby',
  'back',
  'badge',
  'bag',
  'bait',
  'balance',
  'ball',
  'balloon',
  'balls',
  'banana',
  'band',
  'base',
  'baseball',
  'basin',
  'basket',
  'basketball',
  'bat',
  'bath',
  'battle',
  'bead',
  'beam',
  'bean',
  'bear',
  'bears',
  'beast',
  'bed',
  'bedroom',
  'beds',
  'bee',
  'beef',
  'beetle',
  'beggar',
  'beginner',
  'behavior',
  'belief',
  'believe',
  'bell',
  'bells',
  'berry',
  'bike',
  'bikes',
  'bird',
  'birds',
  'birth',
  'birthday',
  'bit',
  'bite',
  'blade',
  'blood',
  'blow',
  'board',
  'boat',
  'boats',
  'body',
  'bomb',
  'bone',
  'book',
  'books',
  'boot',
  'border',
  'bottle',
  'boundary',
  'box',
  'boy',
  'boys',
  'brain',
  'brake',
  'branch',
  'brass',
  'bread',
  'breakfast',
  'breath',
  'brick',
  'bridge',
  'brother',
  'brothers',
  'brush',
  'bubble',
  'bucket',
  'building',
  'bulb',
  'bun',
  'burn',
  'burst',
  'bushes',
  'business',
  'butter',
  'button',
  'cabbage',
  'cable',
  'cactus',
  'cake',
  'cakes',
  'calculator',
  'calendar',
  'camera',
  'camp',
  'can',
  'cannon',
  'canvas',
  'cap',
  'caption',
  'car',
  'card',
  'care',
  'carpenter',
  'carriage',
  'cars',
  'cart',
  'cast',
  'cat',
  'cats',
  'cattle',
  'cause',
  'cave',
  'celery',
  'cellar',
  'cemetery',
  'cent',
  'chain',
  'chair',
  'chairs',
  'chalk',
  'chance',
  'change',
  'channel',
  'cheese',
  'cherries',
  'cherry',
  'chess',
  'chicken',
  'chickens',
  'children',
  'chin',
  'church',
  'circle',
  'clam',
  'class',
  'clock',
  'clocks',
  'cloth',
  'cloud',
  'clouds',
  'clover',
  'club',
  'coach',
  'coal',
  'coast',
  'coat',
  'cobweb',
  'coil',
  'collar',
  'color',
  'comb',
  'comfort',
  'committee',
  'company',
  'comparison',
  'competition',
  'condition',
  'connection',
  'control',
  'cook',
  'copper',
  'copy',
  'cord',
  'cork',
  'corn',
  'cough',
  'country',
  'cover',
  'cow',
  'cows',
  'crack',
  'cracker',
  'crate',
  'crayon',
  'cream',
  'creator',
  'creature',
  'credit',
  'crib',
  'crime',
  'crook',
  'crow',
  'crowd',
  'crown',
  'crush',
  'cry',
  'cub',
  'cup',
  'current',
  'curtain',
  'curve',
  'cushion',
  'dad',
  'daughter',
  'day',
  'death',
  'debt',
  'decision',
  'deer',
  'degree',
  'design',
  'desire',
  'desk',
  'destruction',
  'detail',
  'development',
  'digestion',
  'dime',
  'dinner',
  'dinosaurs',
  'direction',
  'dirt',
  'discovery',
  'discussion',
  'disease',
  'disgust',
  'distance',
  'distribution',
  'division',
  'dock',
  'doctor',
  'dog',
  'dogs',
  'doll',
  'dolls',
  'donkey',
  'door',
  'downtown',
  'drain',
  'drawer',
  'dress',
  'drink',
  'driving',
  'drop',
  'drug',
  'drum',
  'duck',
  'ducks',
  'dust',
  'ear',
  'earth',
  'earthquake',
  'edge',
  'education',
  'effect',
  'egg',
  'eggnog',
  'eggs',
  'elbow',
  'end',
  'engine',
  'error',
  'event',
  'example',
  'exchange',
  'existence',
  'expansion',
  'experience',
  'expert',
  'eye',
  'eyes',
  'face',
  'fact',
  'fairies',
  'fall',
  'family',
  'fan',
  'fang',
  'farm',
  'farmer',
  'father',
  'faucet',
  'fear',
  'feast',
  'feather',
  'feeling',
  'feet',
  'fiction',
  'field',
  'fifth',
  'fight',
  'finger',
  'fire',
  'fireman',
  'fish',
  'flag',
  'flame',
  'flavor',
  'flesh',
  'flight',
  'flock',
  'floor',
  'flower',
  'flowers',
  'fly',
  'fog',
  'fold',
  'food',
  'foot',
  'force',
  'fork',
  'form',
  'fowl',
  'frame',
  'friction',
  'friend',
  'friends',
  'frog',
  'frogs',
  'front',
  'fruit',
  'fuel',
  'furniture',
  'galley',
  'game',
  'garden',
  'gate',
  'geese',
  'ghost',
  'giants',
  'giraffe',
  'girl',
  'girls',
  'glass',
  'glove',
  'glue',
  'goat',
  'gold',
  'goldfish',
  'good-bye',
  'goose',
  'government',
  'governor',
  'grade',
  'grain',
  'grandfather',
  'grandmother',
  'grape',
  'grass',
  'grip',
  'ground',
  'group',
  'growth',
  'guide',
  'guitar',
  'gun',
  'hair',
  'haircut',
  'hall',
  'hammer',
  'hand',
  'hands',
  'harbor',
  'harmony',
  'hat',
  'hate',
  'head',
  'health',
  'hearing',
  'heart',
  'heat',
  'help',
  'hen',
  'hill',
  'history',
  'hobbies',
  'hole',
  'holiday',
  'home',
  'honey',
  'hook',
  'hope',
  'horn',
  'horse',
  'horses',
  'hose',
  'hospital',
  'hot',
  'hour',
  'house',
  'houses',
  'humor',
  'hydrant',
  'ice',
  'icicle',
  'idea',
  'impulse',
  'income',
  'increase',
  'industry',
  'ink',
  'insect',
  'instrument',
  'insurance',
  'interest',
  'invention',
  'iron',
  'island',
  'jail',
  'jam',
  'jar',
  'jeans',
  'jelly',
  'jellyfish',
  'jewel',
  'join',
  'joke',
  'journey',
  'judge',
  'juice',
  'jump',
  'kettle',
  'key',
  'kick',
  'kiss',
  'kite',
  'kitten',
  'kittens',
  'kitty',
  'knee',
  'knife',
  'knot',
  'knowledge',
  'laborer',
  'lace',
  'ladybug',
  'lake',
  'lamp',
  'land',
  'language',
  'laugh',
  'lawyer',
  'lead',
  'leaf',
  'learning',
  'leather',
  'leg',
  'legs',
  'letter',
  'letters',
  'lettuce',
  'level',
  'library',
  'lift',
  'light',
  'limit',
  'line',
  'linen',
  'lip',
  'liquid',
  'list',
  'lizards',
  'loaf',
  'lock',
  'locket',
  'look',
  'loss',
  'love',
  'low',
  'lumber',
  'lunch',
  'lunchroom',
  'machine',
  'magic',
  'maid',
  'mailbox',
  'man',
  'manager',
  'map',
  'marble',
  'mark',
  'market',
  'mask',
  'mass',
  'match',
  'meal',
  'measure',
  'meat',
  'meeting',
  'memory',
  'men',
  'metal',
  'mice',
  'middle',
  'milk',
  'mind',
  'mine',
  'minister',
  'mint',
  'minute',
  'mist',
  'mitten',
  'mom',
  'money',
  'monkey',
  'month',
  'moon',
  'morning',
  'mother',
  'motion',
  'mountain',
  'mouth',
  'move',
  'muscle',
  'music',
  'nail',
  'name',
  'nation',
  'neck',
  'need',
  'needle',
  'nerve',
  'nest',
  'net',
  'news',
  'night',
  'noise',
  'north',
  'nose',
  'note',
  'notebook',
  'number',
  'nut',
  'oatmeal',
  'observation',
  'ocean',
  'offer',
  'office',
  'oil',
  'operation',
  'opinion',
  'orange',
  'oranges',
  'order',
  'organization',
  'ornament',
  'oven',
  'owl',
  'owner',
  'page',
  'pail',
  'pain',
  'paint',
  'pan',
  'pancake',
  'paper',
  'parcel',
  'parent',
  'park',
  'part',
  'partner',
  'party',
  'passenger',
  'paste',
  'patch',
  'payment',
  'peace',
  'pear',
  'pen',
  'pencil',
  'person',
  'pest',
  'pet',
  'pets',
  'pickle',
  'picture',
  'pie',
  'pies',
  'pig',
  'pigs',
  'pin',
  'pipe',
  'pizzas',
  'place',
  'plane',
  'planes',
  'plant',
  'plantation',
  'plants',
  'plastic',
  'plate',
  'play',
  'playground',
  'pleasure',
  'plot',
  'plough',
  'pocket',
  'point',
  'poison',
  'police',
  'polish',
  'pollution',
  'popcorn',
  'porter',
  'position',
  'pot',
  'potato',
  'powder',
  'power',
  'price',
  'print',
  'prison',
  'process',
  'produce',
  'profit',
  'property',
  'prose',
  'protest',
  'pull',
  'pump',
  'punishment',
  'purpose',
  'push',
  'quarter',
  'quartz',
  'queen',
  'question',
  'quicksand',
  'quiet',
  'quill',
  'quilt',
  'quince',
  'quiver',
  'rabbit',
  'rabbits',
  'rail',
  'railway',
  'rain',
  'rainstorm',
  'rake',
  'range',
  'rat',
  'rate',
  'ray',
  'reaction',
  'reading',
  'reason',
  'receipt',
  'recess',
  'record',
  'regret',
  'relation',
  'religion',
  'representative',
  'request',
  'respect',
  'rest',
  'reward',
  'rhythm',
  'rice',
  'riddle',
  'rifle',
  'ring',
  'rings',
  'river',
  'road',
  'robin',
  'rock',
  'rod',
  'roll',
  'roof',
  'room',
  'root',
  'rose',
  'route',
  'rub',
  'rule',
  'run',
  'sack',
  'sail',
  'salt',
  'sand',
  'scale',
  'scarecrow',
  'scarf',
  'scene',
  'scent',
  'school',
  'science',
  'scissors',
  'screw',
  'sea',
  'seashore',
  'seat',
  'secretary',
  'seed',
  'selection',
  'self',
  'sense',
  'servant',
  'shade',
  'shake',
  'shame',
  'shape',
  'sheep',
  'sheet',
  'shelf',
  'ship',
  'shirt',
  'shock',
  'shoe',
  'shoes',
  'shop',
  'show',
  'side',
  'sidewalk',
  'sign',
  'silk',
  'silver',
  'sink',
  'sister',
  'sisters',
  'size',
  'skate',
  'skin',
  'skirt',
  'sky',
  'slave',
  'sleep',
  'sleet',
  'slip',
  'slope',
  'smash',
  'smell',
  'smile',
  'smoke',
  'snail',
  'snails',
  'snake',
  'snakes',
  'sneeze',
  'snow',
  'soap',
  'society',
  'sock',
  'soda',
  'sofa',
  'son',
  'song',
  'songs',
  'sort',
  'sound',
  'soup',
  'space',
  'spade',
  'spark',
  'spiders',
  'sponge',
  'spoon',
  'spot',
  'spring',
  'spy',
  'square',
  'squirrel',
  'stage',
  'stamp',
  'star',
  'start',
  'statement',
  'station',
  'steam',
  'steel',
  'stem',
  'step',
  'stew',
  'stick',
  'sticks',
  'stitch',
  'stocking',
  'stomach',
  'stone',
  'stop',
  'store',
  'story',
  'stove',
  'stranger',
  'straw',
  'stream',
  'street',
  'stretch',
  'string',
  'structure',
  'substance',
  'sugar',
  'suggestion',
  'suit',
  'summer',
  'sun',
  'support',
  'surprise',
  'sweater',
  'swim',
  'swing',
  'system',
  'table',
  'tail',
  'talk',
  'tank',
  'taste',
  'tax',
  'teaching',
  'team',
  'teeth',
  'temper',
  'tendency',
  'tent',
  'territory',
  'test',
  'texture',
  'theory',
  'thing',
  'things',
  'thought',
  'thread',
  'thrill',
  'throat',
  'throne',
  'thumb',
  'thunder',
  'ticket',
  'tiger',
  'time',
  'tin',
  'title',
  'toad',
  'toe',
  'toes',
  'tomatoes',
  'tongue',
  'tooth',
  'toothbrush',
  'toothpaste',
  'top',
  'touch',
  'town',
  'toy',
  'toys',
  'trade',
  'trail',
  'train',
  'trains',
  'tramp',
  'transport',
  'tray',
  'treatment',
  'tree',
  'trees',
  'trick',
  'trip',
  'trouble',
  'trousers',
  'truck',
  'trucks',
  'tub',
  'turkey',
  'turn',
  'twig',
  'twist',
  'umbrella',
  'uncle',
  'underwear',
  'unit',
  'use',
  'vacation',
  'value',
  'van',
  'vase',
  'vegetable',
  'veil',
  'vein',
  'verse',
  'vessel',
  'vest',
  'view',
  'visitor',
  'voice',
  'volcano',
  'volleyball',
  'voyage',
  'walk',
  'wall',
  'war',
  'wash',
  'waste',
  'watch',
  'water',
  'wave',
  'waves',
  'wax',
  'way',
  'wealth',
  'weather',
  'week',
  'weight',
  'wheel',
  'whip',
  'whistle',
  'wilderness',
  'wind',
  'window',
  'wine',
  'wing',
  'winter',
  'wire',
  'wish',
  'woman',
  'women',
  'wood',
  'wool',
  'word',
  'work',
  'worm',
  'wound',
  'wren',
  'wrench',
  'wrist',
  'writer',
  'writing',
  'yak',
  'yam',
  'yard',
  'yarn',
  'year',
  'yoke',
  'zebra',
  'zephyr',
  'zinc',
  'zipper',
  'zoo',
]
