import React, { memo } from 'react'
import { Input } from '@/components/ui/input'
import { X } from 'lucide-react'

interface BatchEntry {
  id: string
  address: string
  label: string
  addressError?: string
  labelError?: string
}

interface BatchEntryRowProps {
  entry: BatchEntry
  index: number
  parentName: string
  showBatchSeparator: boolean
  batchLabel: string
  isAutoGenerated: boolean
  canRemove: boolean
  focusedInputId: string | null
  shouldTruncateAddress: Record<string, boolean>
  truncatedAddresses: Record<string, string>
  onUpdate: (id: string, field: 'address' | 'label', value: string) => void
  onRemove: (id: string) => void
  onFocus: (id: string) => void
  onBlur: (id: string, address: string) => void
  addressInputRef: (el: HTMLInputElement | null) => void
}

export const BatchEntryRow = memo(function BatchEntryRow({
  entry,
  parentName,
  showBatchSeparator,
  batchLabel,
  isAutoGenerated,
  canRemove,
  focusedInputId,
  shouldTruncateAddress,
  truncatedAddresses,
  onUpdate,
  onRemove,
  onFocus,
  onBlur,
  addressInputRef,
}: BatchEntryRowProps) {
  return (
    <div className="space-y-1">
      {showBatchSeparator && (
        <div className="flex items-center gap-2 py-2">
          <div className="flex-1 h-px bg-gradient-to-r from-blue-400 via-blue-500 to-blue-400 dark:from-blue-600 dark:via-blue-500 dark:to-blue-600"></div>
          <span className="text-xs font-semibold text-blue-600 dark:text-blue-400 px-2 whitespace-nowrap">
            Batch: {batchLabel}
          </span>
          <div className="flex-1 h-px bg-gradient-to-r from-blue-400 via-blue-500 to-blue-400 dark:from-blue-600 dark:via-blue-500 dark:to-blue-600"></div>
        </div>
      )}
      {isAutoGenerated && (
        <div className="flex items-center gap-1 mb-1 px-2 py-1 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded text-xs text-amber-700 dark:text-amber-300">
          <span className="font-semibold">ℹ️ Auto-created:</span>
          <span>Parent subname with no forward resolution</span>
        </div>
      )}
      <div className={`flex items-start gap-2 ${isAutoGenerated ? 'opacity-75' : ''}`}>
        <div className="flex-1 space-y-1 min-w-0">
          <div className="relative">
            <Input
              ref={addressInputRef}
              type="text"
              placeholder="Contract Address"
              value={entry.address}
              onChange={(e) => onUpdate(entry.id, 'address', e.target.value)}
              onFocus={() => onFocus(`${entry.id}-address`)}
              onBlur={() => onBlur(entry.id, entry.address)}
              className={`w-full px-4 py-2 bg-white text-black dark:text-white dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-sm ${
                entry.addressError
                  ? 'border-red-500 dark:border-red-500 focus:ring-red-500'
                  : ''
              } ${
                shouldTruncateAddress[entry.id] &&
                focusedInputId !== `${entry.id}-address`
                  ? 'text-transparent'
                  : ''
              }`}
            />
            {entry.address &&
              shouldTruncateAddress[entry.id] &&
              focusedInputId !== `${entry.id}-address` &&
              truncatedAddresses[entry.id] && (
                <div className="absolute inset-0 px-4 py-2 pointer-events-none flex items-center">
                  <span className="text-gray-900 dark:text-gray-200 text-sm whitespace-nowrap">
                    {truncatedAddresses[entry.id]}
                  </span>
                </div>
              )}
          </div>
          {entry.addressError && (
            <p className="text-xs text-red-600 dark:text-red-400 ml-1">
              {entry.addressError}
            </p>
          )}
        </div>
        <div className="flex-1 space-y-1 min-w-0">
          <Input
            type="text"
            placeholder={`myawesomeapp.${parentName || 'domain.eth'}`}
            value={entry.label}
            onChange={(e) => onUpdate(entry.id, 'label', e.target.value)}
            className={`w-full px-4 py-2 bg-white text-black dark:text-white dark:bg-gray-700 border-gray-300 dark:border-gray-600 ${
              entry.labelError
                ? 'border-red-500 dark:border-red-500 focus:ring-red-500'
                : ''
            }`}
            style={{
              textOverflow: 'ellipsis',
              overflow: 'hidden',
              whiteSpace: 'nowrap',
            }}
          />
          {entry.labelError && (
            <p className="text-xs text-red-600 dark:text-red-400 ml-1">
              {entry.labelError}
            </p>
          )}
        </div>
        {canRemove && (
          <button
            onClick={() => onRemove(entry.id)}
            className="p-2 text-gray-400 hover:text-red-600 dark:hover:text-red-400 rounded mt-0.5"
          >
            <X className="w-5 h-5" />
          </button>
        )}
      </div>
    </div>
  )
})
